Q1. Understanding Feature Distributions (Iris Dataset)

Context: Before training any ML model, we analyze feature distributions.

Dataset: Load Iris dataset from sklearn

Tasks:

1. Extract feature matrix as NumPy array
2. Compute:
Mean
Median
Standard deviation
Variance (for each feature)
3. Identify:
Which feature has highest variability and why it matters in ML
4. Convert any one feature into shape (n,1) and explain why ML models expect this format

In [17]:
## installl scikit-learn package using below code:
## %pip install scikit-learn

# import iris dataset 
from sklearn.datasets import load_iris

# import NumPy module
import numpy as np

# load the iris dataset
iris = load_iris()

# extract the feature matrix as NumPy array
iris_np_arr = iris.data
print(iris_np_arr)

# computation of Mean, Median, Standard deviation and Variance (for each feature)
print("2) Computation for each feature:")
# mean for each feature (column wise)
iris_mean = np.mean(iris_np_arr, axis=0)
print(iris_mean)

# median for each feature (column wise)
iris_median = np.median(iris_np_arr, axis=0)
print(f"   Median: {iris_median}")

# standard deviation for each feature (column wise)
iris_std = np.std(iris_np_arr, axis=0)
print(f"   Standard Deviation: {iris_std}")

# variance for each feature (column wise)
iris_var = np.var(iris_np_arr, axis=0)
print(f"   Varience: {iris_var}")

# use argmax to identify highest variability feature
iris_var_max = np.argmax(iris_var)
print(iris_var_max)
print("""Why it matters in ML?
Explaination: Data in 3rd column is not same and it is highly different with each row.
More the difference in the data for each feature make ML can see patterns and learns well""")


# conversion of one feature (column) into shape (n,1) 
# slice the complete 3rd column
iris_col3 = iris_np_arr[:, 3]

# reshape the 3rd column feature matrix
iris_cols3_reshaped = iris_col3.reshape(-1,1)
print(iris_cols3_reshaped)
print("""Explain why ML models expect this format?
Explaination: We convert 2D array to 1D array for ease
to do calculations, perform operations, indexing and
to apply various functions.
""")


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

Q2. Data Selection for Model Input

Context: Models are trained on selective features, not full raw data.

Dataset: Iris

Tasks:

1. Extract:
First 100 samples
Only last 2 features
2. Use boolean masking:
Select samples where petal length is greater than dataset mean
3. Count selected samples
4. Explain how this relates to feature-based filtering in ML

In [38]:
# import iris dataset 
from sklearn.datasets import load_iris

# import NumPy module
import numpy as np

# load the iris dataset
iris = load_iris()

# extract the feature matrix as NumPy array
iris_np_arr = iris.data

# extract 100 rows and 2 columns by using slicing
print(iris_np_arr[0:100,2:4])

# boolean masking: petal length > dataset mean
masked = iris_np_arr[:,3]>iris_np_arr[:2].mean()
print(masked)

# count selected samples
print(np.sum(masked))

# explanation feature-based filtering in ML
print("""Relation to Feature-based filtering in ML:
We filter important data and ignore unnecessary data so the model finds patterns easily.
""")


[[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [1.7 0.4]
 [1.4 0.3]
 [1.5 0.2]
 [1.4 0.2]
 [1.5 0.1]
 [1.5 0.2]
 [1.6 0.2]
 [1.4 0.1]
 [1.1 0.1]
 [1.2 0.2]
 [1.5 0.4]
 [1.3 0.4]
 [1.4 0.3]
 [1.7 0.3]
 [1.5 0.3]
 [1.7 0.2]
 [1.5 0.4]
 [1.  0.2]
 [1.7 0.5]
 [1.9 0.2]
 [1.6 0.2]
 [1.6 0.4]
 [1.5 0.2]
 [1.4 0.2]
 [1.6 0.2]
 [1.6 0.2]
 [1.5 0.4]
 [1.5 0.1]
 [1.4 0.2]
 [1.5 0.2]
 [1.2 0.2]
 [1.3 0.2]
 [1.4 0.1]
 [1.3 0.2]
 [1.5 0.2]
 [1.3 0.3]
 [1.3 0.3]
 [1.3 0.2]
 [1.6 0.6]
 [1.9 0.4]
 [1.4 0.3]
 [1.6 0.2]
 [1.4 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [4.7 1.4]
 [4.5 1.5]
 [4.9 1.5]
 [4.  1.3]
 [4.6 1.5]
 [4.5 1.3]
 [4.7 1.6]
 [3.3 1. ]
 [4.6 1.3]
 [3.9 1.4]
 [3.5 1. ]
 [4.2 1.5]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]
 [4.4 1.4]
 [4.5 1.5]
 [4.1 1. ]
 [4.5 1.5]
 [3.9 1.1]
 [4.8 1.8]
 [4.  1.3]
 [4.9 1.5]
 [4.7 1.2]
 [4.3 1.3]
 [4.4 1.4]
 [4.8 1.4]
 [5.  1.7]
 [4.5 1.5]
 [3.5 1. ]
 [3.8 1.1]
 [3.7 1. ]
 [3.9 1.2]
 [5.1 1.6]
 [4.5 1.5]
 [4.5 1.6]
 [4.7 1.5]
 [4.4 1.3]
 [4.1 1.3]
 [4.  1.3]
 [4.4 1.2]

Q3. Feature Scaling using NumPy (Very Important)

Context: Most ML models require normalized data.

Dataset: Iris (NumPy array)

Tasks:

1. Apply standardization:

$$
X' = \frac{X - \mu}{\sigma}
$$
	​2. 

Verify:
Mean ≈ 0
Std ≈
on

In [43]:
# import iris dataset 
from sklearn.datasets import load_iris

# import NumPy module
import numpy as np

# load the iris dataset
iris = load_iris()

# extract the feature matrix as NumPy array
iris_np_arr = iris.data

# mean
iris_mean = np.mean(iris_np_arr, axis=0)

# standard deviation
iris_std = np.std(iris_np_arr, axis=0)

# apply formula: Numpy Array - Mean / Standard Deviation
iris_standarised= ((iris_np_arr-iris_mean)/iris_std)

# verifying standarised mean to zero
print(np.mean(iris_standarised, axis=0))

# verifying standarised stanndard deviation to zero
print(np.std(iris_standarised, axis=0))

[-1.69031455e-15 -1.84297022e-15 -1.69864123e-15 -1.40924309e-15]
[1. 1. 1. 1.]


Q4. Dataset Understanding (Titanic Dataset)

Context: First step in ML pipeline is dataset inspection.

Dataset: Titanic (Seaborn)

Tasks:

1. Display:
head(), tail()
info(), describe()
2. Identify:
Missing values per column
Numerical vs categorical features
3. Explain:
Why identifying feature types is important before modeling

In [54]:
# import seaborn module
import seaborn as sns

# import pandas as 
#load Titanic dataset
data = sns.load_dataset("Titanic")

# display: first 5 rows from dataset
# print(data.head())
# print(data.tail())
# print(data.info())
# print(data.describe())

# identifying missing values per column
print(data.isnull().sum())




survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64


Q5. Filtering Data for Business Logic

Context: Real ML problems require filtering relevant populations.

Dataset: Titanic

Tasks:

1. Filter:
Female passengers in 1st class
2. Compute:
Survival rate for this group
3. Compare with overall survival rate
4. Interpret:
What insight can be used in ML feature engineering

In [8]:
import seaborn as sns
import pandas as pd
import numpy as np

# load the Titanic dataset from seaborn module
df = sns.load_dataset("Titanic")

# filter by female passenger in first class
data_fm_first = df[(df['sex'] == 'female') & (df['class'] == 'First')]
print(data_fm)

# survival rate for the above group
group_survival_rate_fm_first = data_fm_first['survived'].mean()
print(group_survival_rate_fm_first)

# overall survival rate
overall_survival_rate = df['survived'].mean()
print(overall_survival_rate)


# inteprtation
print("""After looking at the above data of female first class survival rate
with overall survival rate, a insights can be used in ML feature engineering is that in Titanic
the female passengers from first class have hhigher survival rate.""")

     survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
1           1       1  female  38.0      1      0   71.2833        C  First   
3           1       1  female  35.0      1      0   53.1000        S  First   
11          1       1  female  58.0      0      0   26.5500        S  First   
31          1       1  female   NaN      1      0  146.5208        C  First   
52          1       1  female  49.0      1      0   76.7292        C  First   
..        ...     ...     ...   ...    ...    ...       ...      ...    ...   
856         1       1  female  45.0      1      1  164.8667        S  First   
862         1       1  female  48.0      0      0   25.9292        S  First   
871         1       1  female  47.0      1      1   52.5542        S  First   
879         1       1  female  56.0      0      1   83.1583        C  First   
887         1       1  female  19.0      0      0   30.0000        S  First   

       who  adult_male deck  embark_town alive  alo

Q6. Handling Missing Data (Critical ML Step)

Context: Models cannot handle null values.

Dataset: Titanic

Tasks:

1. Fill missing age using median
2. Fill missing embarked using mode
3. Drop deck column
4. Explain:
Why different strategies are used for different columns

In [18]:
import seaborn as sns
import pandas as pd
import numpy as np

# load the Titanic dataset from seaborn module
df = sns.load_dataset("Titanic")

# check all missing values from column
df.isnull().sum()

# fill the 177 missing value of age with age median
df['age'].fillna(df['age'].median())

# fill the 2 missing embarked value using mode
df['embarked'].fillna(df['embarked'].mode()[0])

# drop deck column
df.drop(columns=['deck'])

# explanation for using different strategies for different columns
print("""Different strategies are used because columns with different data types
with their missing values need different ways of handling so the data stays good 
and the model works better. For example: Numerical missing data with median, 
categorical with mode and useless and shrewed data column to be dropped.""")



Different strategies are used because columns with different data types
with their missing values need different ways of handling so the data stays good 
and the model works better. For example: Numerical missing data with median, 
categorical with mode and useless and shrewed data column to be dropped.


Q7. Feature Engineering for Model Improvement

Context: Raw data is rarely useful—features must be created.

Dataset: Titanic

Tasks:

1. Create:
family_size = sibsp + parch + 1
2. Create:
is_alone (binary feature)
3. Compute survival rate by is_alone
4. Explain:
Why engineered features improve ML models

In [23]:
import seaborn as sns
import pandas as pd
import numpy as np

# load the Titanic dataset from seaborn module
df = sns.load_dataset("Titanic")

# create a new column of family size
df['family_size'] = df['sibsp'] + df['parch'] + 1

# create a ne binary feature "is_alone"
df['is_alone'] = (df['family_size'] == 1).astype(int)

# computation of survival rate of is_alone feature
df.groupby('is_alone')['survived'].mean()

# explaination 
print("""Engineered features improves ML models 
because they turn basic raw data 
into useful patterns that the model can learn easily.""")

Engineered features improves ML models 
because they turn basic raw data 
into useful patterns that the model can learn easily.


Q8. Group-Based Insights (Customer Segmentation Logic)

Context: ML models often depend on aggregated patterns.

Dataset: Tips

Tasks:

1. Compute:
Average tip by day
Total bill by gender
2. Create new feature:
tip_percentage
3. Identify:
Which day has highest tipping behavior
4. Explain:
How this helps in segmentation models

In [33]:
import seaborn as sns
import pandas as pd
import numpy as np

# load the Tips dataset from seaborn module
df = sns.load_dataset("Tips")

# computation of average tip by day's total bill
df.groupby('day')['tip'].mean()

# computation of total bill by gender
df.groupby('sex')['total_bill'].sum()

# identification of highest tipping day
df['tip_percentage'] = df['tip'] / df['total_bill'] # tip percentage
df.groupby('day')['tip_percentage'].mean().idxmax()



'Fri'

Q9. Advanced Filtering + Subsetting

Context: Training data is often filtered based on business rules.

Dataset: Tips

Tasks:

1. Filter:
total_bill > 20 AND tip < 3
2. Select only relevant columns
3. Analyze:
Is this segment under-tipping?
4. Explain:
How such filtering helps anomaly detection

In [43]:
import seaborn as sns
import pandas as pd
import numpy as np

# load the Tips dataset from seaborn module
df = sns.load_dataset("Tips")

# filter  total_bill > 20 AND tip < 3
filtered_cols = df[(df['total_bill'] > 20) & (df['tip'] < 3)]
print(filtered)

# select only relevant columns
relevant_cols = filtered_cols[['total_bill', 'tip', 'day', 'time']]
print(relevant_cols)

# to know the above filtered segment is under-tipping
# need to calculate percentage tip of filtered segment
# and compare with overall percentage
filtered_cols['tip_percentage'] = filtered_cols['tip'] / filtered_cols['total_bill']
print(filtered_cols['tip_percentage'].mean())

df['tip_percentage'] = df['tip'] / df['total_bill']
print(df['tip_percentage'].mean())

# explanation 
print("""Overall Tip percentage is found to be around 16%
whereas filtered segment of 9% hence the filtered segment
is under-tipping.""")

     total_bill   tip     sex smoker   day    time  size
21        20.29  2.75  Female     No   Sat  Dinner     2
33        20.69  2.45  Female     No   Sat  Dinner     4
48        28.55  2.05    Male     No   Sun  Dinner     3
57        26.41  1.50  Female     No   Sat  Dinner     2
68        20.23  2.01    Male     No   Sat  Dinner     2
102       44.30  2.50  Female    Yes   Sat  Dinner     3
113       23.95  2.55    Male     No   Sun  Dinner     2
119       24.08  2.92  Female     No  Thur   Lunch     4
129       22.82  2.18    Male     No  Thur   Lunch     3
131       20.27  2.83  Female     No  Thur   Lunch     2
153       24.55  2.00    Male     No   Sun  Dinner     4
166       20.76  2.24    Male     No   Sun  Dinner     2
187       30.46  2.00    Male    Yes   Sun  Dinner     5
192       28.44  2.56    Male    Yes  Thur   Lunch     2
208       24.27  2.03    Male    Yes   Sat  Dinner     2
210       30.06  2.00    Male    Yes   Sat  Dinner     3
229       22.12  2.88  Female  

Q10. Data Transformation for Model Input (NumPy)

Context: ML models require structured numeric arrays.

Tasks:

1. Create two arrays of shape (3,2)
2. Perform:
Vertical stacking
Horizontal stacking
3. Reshape into (2,6)
4. Explain:
Why reshaping is required in ML pipelines

In [49]:
import numpy as np

# create a two arrays with shape (3,2)
arr_1 = np.array([[1, 2],[3, 4],[5, 6]])
arr_2 = np.array([[7, 8],[9,10],[11,12]])

# vertical stacking
arr_vstacked = np.vstack((arr_1, arr_2))
print(arr_vstacked)

# horizontal stacking
arr_hstacked = np.hstack((arr_1, arr_2))
print(arr_hstacked)

# reshaping above vertical stacked into (2,6)
arr_reshaped = arr_vstacked.reshape(2,6)
print(arr_reshaped)

# reshaping above horizontal stacked into (2,6)
arr_reshaped = arr_hstacked.reshape(2,6)
print(arr_reshaped)

# explaination
print("""Reshaping is required in ML pipelines because 
ML models need data in the correct row and column form 
to understand data and features properly.""")


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  7  8  3  4]
 [ 9 10  5  6 11 12]]
Reshaping is required in ML pipelines because 
ML models need data in the correct row and column form 
to understand data and features properly.


Q11. End-to-End ML Preprocessing Pipeline (Titanic)

Context: Prepare dataset for ML model training

Tasks:

1. Load dataset
2. Handle missing values
3. Encode categorical variables (sex, embarked)
4. Normalize numerical features
5. Convert to NumPy array

Output:

Final feature matrix ready for model training

In [56]:
import seaborn as sns
import pandas as pd
import numpy as np

# load the Titanic dataset from seaborn module
df = sns.load_dataset("Titanic")


# handling missing values
# firstly check all missing values from column
df.isnull().sum()

# secondly fill the 177 missing value of age with age median
df['age'].fillna(df['age'].median())

# thirdly fill the 2 missing embarked value using mode
df['embarked'].fillna(df['embarked'].mode()[0])


## encoding categorical variables
# encoding sex column
df['sex'] = df['sex'].map({'male':0,'female':1})

# encoding embarked column
df['embarked'] = df['embarked'].map({'C':0,'Q':1,'S':2})


## normalise numerical data like age and fare
# select only age and fare columns
df_age_fare = df[['age','fare']]
print(df_age_fare)

# normalising age and fare
nm = (df_age_fare - df_age_fare.mean(axis=0)) / df_age_fare.std(axis=0)
print(nm)


# convert to Numpy Array
df_np = df_age_fare.values
print(df_np)



      age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]
[[22.      7.25  ]
 [38.     71.2833]
 [26.      7.925 ]
 ...
 [    nan 23.45  ]
 [26.     30.    ]
 [32.      7.75  ]]
          age      fare
0   -0.530005 -0.502163
1    0.571430  0.786404
2   -0.254646 -0.488580
3    0.364911  0.420494
4    0.364911 -0.486064
..        ...       ...
886 -0.185807 -0.386454
887 -0.736524 -0.044356
888       NaN -0.176164
889 -0.254646 -0.044356
890  0.158392 -0.492101

[891 rows x 2 columns]


Q12. Feature Selection using Statistical Understanding

Context: Not all features improve model performance.

Dataset: Iris

Tasks:

1. Compute correlation matrix
2. Identify highly correlated features
3. Drop redundant features
4. Explain:
Impact on overfitting and model performance

In [3]:
# import iris dataset 
from sklearn.datasets import load_iris
# import NumPy module and Pandas
import numpy as np
import pandas as pd

# load the iris dataset
iris = load_iris()

# extract the feature matrix as NumPy array
iris_np_arr = iris.data
print(iris_np_arr)

# computation of correlation matrix
df = pd.DataFrame(iris_np_arr, columns=iris.feature_names)
df_corr_matrix = df.corr()
print(df_corr_matrix)

# dropping redundant feature
df_reduced = df.drop(columns=['petal width (cm)'])
print(df_reduced)

# explaination  of impact on overfitting and model performances
print("""Removing extra and similar columns helps stop overfitting 
and makes the model faster, easier, and more accurate.""")

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

Q13. Custom Feature Transformation using apply()

Context: Real ML requires custom logic transformation.

Dataset: Titanic

Tasks:

1. Create age_group:
Child / Adult / Senior
2. Use .apply()
3. Compute survival rate per group
4. Interpret:
Which segment has highest survival likelihood

In [8]:
import seaborn as sns
import pandas as pd
import numpy as np

# load the Titanic dataset from seaborn module
df = sns.load_dataset("Titanic")


## creating a new feature age_group
# function to define age group
def age_group(age):
    if age < 18:
        return 'Child'
    elif age < 60:
        return 'Adult'
    else:
        return 'Senior'
        
# using apply function of Pandas module
df['age_group'] = df['age'].apply(age_group)
print(df)

# computation of survival rate per age group
print(df.groupby('age_group')['survived'].mean())

# interpretation of the highest survival rate
print(df.groupby('age_group')['survived'].mean().idxmax())



     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alo

Q14. Error Analysis Simulation (Model Evaluation Thinking)

Context: Understanding prediction errors is key in ML.

Tasks:

1. Generate 1000 random error values using NumPy
2. Compute:
Mean
Standard deviation
3. Identify outliers:
Using mean ± 2*std
4. Explain:
What high variance means in model performance

In [11]:
import numpy as np

# generate 1000 random error values using Numpy module
error_nums = np.random.randn(1000)
print(error_nums)

# computation of mean and standard deviation
error_num_mean = np.mean(error_nums)
error_num_std = np.std(error_nums)

print(error_num_mean)
print(error_num_std)

# identify outliers: using mean ± 2*std
error_num_lower = error_num_mean - 2*std
error_num_upper = error_num_mean + 2*std

outliers = error_nums[(error_nums < error_num_lower) | (error_nums > error_num_upper)]
print(len(outliers))

# explain: What high variance means in model performance
print("""High variance means the model makes different-sized mistakes again and again, 
showing overfitting and weak performance on new new data.""")


[ 2.17015058e-01  1.37897947e+00 -1.44145387e+00  5.55322221e-01
 -1.51924285e+00  6.35898477e-01  7.10166438e-01 -1.20302576e+00
  2.61908537e+00  8.59333022e-01  1.30587544e+00 -2.99664520e+00
 -5.76644296e-01 -2.69227553e-01  5.51865738e-01 -6.07119695e-02
  1.26338510e+00 -1.05520470e+00 -9.19907966e-01  1.83154768e-01
 -7.89135499e-01 -1.26739342e+00 -2.41430302e+00 -7.74451604e-01
  1.25904978e+00 -1.51086318e-01 -3.70339091e-01 -9.91845442e-01
 -2.45470815e-01 -9.62163924e-01 -1.49399627e-02  2.29423976e-01
  2.82623733e-01 -9.40589579e-01  6.83150562e-01  5.90112058e-01
  5.66826135e-02  9.28844834e-01 -5.87474407e-01 -6.65188705e-01
 -5.37142118e-02 -2.86986464e-02 -3.57996532e-01  5.76176280e-01
  3.38515065e-01  2.08099144e-01 -1.23701164e+00 -7.44743879e-03
  4.05667073e-01 -1.36187940e+00 -8.62694488e-03 -1.31972190e+00
  8.27864398e-01 -1.19082772e+00  7.45074928e-01  5.97548527e-01
 -5.67925395e-02  2.67999659e-01  1.60504290e+00  4.82619770e-02
 -2.74413800e+00 -3.37907

Q15. Business + ML Insight Problem (Tips Dataset)

Context: Convert data analysis into decision-making

Tasks:

1. Create:
tip_percentage
2. Group by:
day and time
3. Identify:
Highest revenue segment
4. Provide:
Recommendation for business strategy
How ML model can use this insight

In [20]:
import seaborn as sns
import pandas as pd
import numpy as np

# load the Tips dataset from seaborn module
df = sns.load_dataset("Tips")

# compute tip percentage as new feature
df['tip_percentage'] = df['tip'] / df['total_bill']
print(df)

# grouping of total amount of bill by day and time
revenue=df.groupby(['day', 'time'])['total_bill'].sum()
print(earnings)

# highest revenue segment
print(revenue.idxmax())

# business strategy
print("""Business can give more attention to times when earnings are high, 
and ML can use day and time to predict sales, crowd, and future customers.""")

     total_bill   tip     sex smoker   day    time  size  tip_percentage
0         16.99  1.01  Female     No   Sun  Dinner     2        0.059447
1         10.34  1.66    Male     No   Sun  Dinner     3        0.160542
2         21.01  3.50    Male     No   Sun  Dinner     3        0.166587
3         23.68  3.31    Male     No   Sun  Dinner     2        0.139780
4         24.59  3.61  Female     No   Sun  Dinner     4        0.146808
..          ...   ...     ...    ...   ...     ...   ...             ...
239       29.03  5.92    Male     No   Sat  Dinner     3        0.203927
240       27.18  2.00  Female    Yes   Sat  Dinner     2        0.073584
241       22.67  2.00    Male    Yes   Sat  Dinner     2        0.088222
242       17.82  1.75    Male     No   Sat  Dinner     2        0.098204
243       18.78  3.00  Female     No  Thur  Dinner     2        0.159744

[244 rows x 8 columns]
day   time  
Fri   Dinner     235.96
      Lunch       89.92
Sat   Dinner    1778.40
Sun   Dinner   